/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class fDaftar extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fDaftar.class.getName());

    /**
     * Creates new form fDaftar
     */
    public fDaftar() {
        initComponents();
          initComponents();
        //agar mudah di tambah dan hapus
        //lstPilih dibuatkan ListModel
        pilih = new DefaultListModel();
        lstPilih.setModel(pilih);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKuliah = new javax.swing.JList<>();
        btnCopy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPilih = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtKuliah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTerpilih = new javax.swing.JTextArea();
        btnHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboAngkatan = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Mata Kuliah");

        lstKuliah.setBackground(new java.awt.Color(255, 204, 204));
        lstKuliah.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java Desktop", "Pemograman Web", "Bahasa Inggris", "Logika dan Algoritma", "Organisasi Komputer", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstKuliah.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKuliahValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKuliah);

        btnCopy.setText(">>");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        jLabel2.setText("Mata Kuliah Terpilih");

        lstPilih.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane2.setViewportView(lstPilih);

        jLabel3.setText("Kuliah yang dipilih");

        txtKuliah.setEditable(false);
        txtKuliah.setBackground(new java.awt.Color(255, 204, 204));
        txtKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKuliahActionPerformed(evt);
            }
        });

        jLabel4.setText("Banyak Mata Kuliah Terpilih");

        txtTerpilih.setEditable(false);
        txtTerpilih.setBackground(new java.awt.Color(255, 204, 204));
        txtTerpilih.setColumns(20);
        txtTerpilih.setRows(5);
        jScrollPane3.setViewportView(txtTerpilih);

        btnHapus.setBackground(new java.awt.Color(255, 204, 204));
        btnHapus.setText("Hapus Terpilih");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel5.setText("Angkatan");

        cboAngkatan.setBackground(new java.awt.Color(255, 204, 204));
        cboAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2008", "2007", "< 2007" }));

        btnHitung.setBackground(new java.awt.Color(255, 204, 204));
        btnHitung.setText("Hitung Biaya");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtResume.setEditable(false);
        txtResume.setBackground(new java.awt.Color(255, 204, 204));
        txtResume.setColumns(20);
        txtResume.setRows(5);
        jScrollPane4.setViewportView(txtResume);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cboAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(btnHitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnCopy)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHitung))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKuliahActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
         // TODO add your handling code here:
        int nPilih=Integer.parseInt(txtTerpilih.getText());
        int i =cboAngkatan.getSelectedIndex();
        String isian=cboAngkatan.getSelectedItem().toString();
        
        //hitung Biaya
        int nPerMK = 0;
        switch (i) {
            case 0:nPerMK = 100000;break;
            case 1:nPerMK = 900000;break;
            case 2:nPerMK = 75000;break;
            default : nPerMK = 500000;
        }
        int nBiaya = nPerMK*nPilih;
        
        //isikan Resume Ke tetxtArean txtResume
        String sResume = "Anda Angkatan:" +isian+"\n"+
                "Banyak Mata Kuliah dipilih:"+
                Integer.toString(nPilih)+"\n"+
                "Biaya Per Mata Kuliah: "+
        Integer.toString(nPerMK)+"\n"+
                "TOTAL BIAYA :"+Integer.toString(nBiaya);
                txtResume.setText(sResume);
                
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
         // TODO add your handling code here:
        //tambahkan tuliasn di lstKuliah yang dipilih
        //ke Dalam ListData Model pilih
        pilih.addElement(lstKuliah.getSelectedValue().toString());
        //setelah ditambah, hitung jumlah pilihan
        int size = pilih.getSize();
        txtTerpilih.setText(Integer.toString(size));
    }//GEN-LAST:event_btnCopyActionPerformed

    private void lstKuliahValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKuliahValueChanged
       // TODO add your handling code here:
        //setiap kali diklik, munculka nama mata kuliah ditxtKuliah
        int index = lstKuliah.getAnchorSelectionIndex();
        String kuliah =lstKuliah.getSelectedValue().toString();
        txtKuliah.setText(kuliah);
    }//GEN-LAST:event_lstKuliahValueChanged

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = lstPilih.getSelectedIndex();
        //yang di-remove adalah listDara model-nya
        pilih.remove(index);
        int size = pilih.getSize();
        txtTerpilih.setText(Integer.toString(size));
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new fDaftar().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> new fDaftar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cboAngkatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstKuliah;
    private javax.swing.JList<String> lstPilih;
    private javax.swing.JTextField txtKuliah;
    private javax.swing.JTextArea txtResume;
    private javax.swing.JTextArea txtTerpilih;
    // End of variables declaration//GEN-END:variables
}
