/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class P_Modul2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(P_Modul2.class.getName());

    /**
     * Creates new form P_Modul2
     */
    public P_Modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        txtEsTeh = new javax.swing.JTextField();
        lblCara = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();
        lblCaraBayar = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoMandiri = new javax.swing.JRadioButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("MENU");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("QUANTITY");

        txtSoto.setBackground(new java.awt.Color(255, 204, 204));
        txtSoto.setText("0");

        txtSate.setBackground(new java.awt.Color(255, 204, 204));
        txtSate.setText("0");

        txtEsJeruk.setBackground(new java.awt.Color(255, 204, 204));
        txtEsJeruk.setText("0");

        btnHitung.setBackground(new java.awt.Color(255, 204, 204));
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        txtEsTeh.setBackground(new java.awt.Color(255, 204, 204));
        txtEsTeh.setText("0");

        lblCara.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblCara.setText("CARA BAYAR");

        btnKosong.setBackground(new java.awt.Color(255, 204, 204));
        btnKosong.setForeground(new java.awt.Color(0, 0, 0));
        btnKosong.setText("KOSONGKAN");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        lblCaraBayar.setText("Cara Bayar:");

        chkSoto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        chkSoto.setText("Soto : Rp.5000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkSate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        chkSate.setText("Sate : Rp 10000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsTeh.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        chkEsTeh.setText("Es Teh : Rp.2000");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        chkEsJeruk.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        chkEsJeruk.setText("Es Jeruk  :  Rp.1500");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        rdoCash.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoCash);
        rdoCash.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rdoCash.setText("Cash");
        rdoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoBCA);
        rdoBCA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rdoBCA.setText("BCA Card");
        rdoBCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBCAActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMandiri);
        rdoMandiri.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        rdoMandiri.setText("Mandiri Card");
        rdoMandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMandiriActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("Rp. 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkSate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(chkEsJeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(chkEsTeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkSoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsTeh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCara)
                            .addComponent(lblCaraBayar)
                            .addComponent(rdoCash)
                            .addComponent(rdoMandiri)
                            .addComponent(rdoBCA))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal)
                                .addGap(51, 51, 51))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsJeruk)
                            .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkSoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkSate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkEsTeh))
                        .addGap(57, 57, 57)))
                .addComponent(btnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblCara)
                .addGap(30, 30, 30)
                .addComponent(rdoCash, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(rdoBCA))
                .addGap(8, 8, 8)
                .addComponent(rdoMandiri)
                .addGap(18, 18, 18)
                .addComponent(btnKosong)
                .addGap(42, 42, 42)
                .addComponent(lblCaraBayar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        if(chkEsJeruk.isSelected()){
            txtEsJeruk.setEditable(true);
            txtEsJeruk.setText("1");
        }else{
            txtEsJeruk.setEditable(false);
            txtEsJeruk.setText("0");
        }
                                  

    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        if(chkSoto.isSelected()){
            txtSoto.setEditable(true);
            txtSoto.setText("1");
        } else {
            txtSoto.setEditable(false);
            txtSoto.setText("0");
        }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void rdoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashActionPerformed
      lblCaraBayar.setText("Cara Bayar : UANG CASH");
    }//GEN-LAST:event_rdoCashActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
if(chkSate.isSelected()){
            txtSate.setEditable(true);
            txtSate.setText("1");
        }else{
            txtSate.setEditable(false);
            txtSate.setText("0");
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
if(chkEsTeh.isSelected()){
            txtEsTeh.setEditable(true);
            txtEsTeh.setText("1");
        }else{
            txtEsTeh.setEditable(false);
            txtEsTeh.setText("0");
        }
                                         
       
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
         boolean IDataOke = true;
          
         if(chkSoto.isSelected()&& txtSoto.getText() == "")
            IDataOke = false;
         if(chkSate.isSelected()&& txtSate.getText() == "")
              IDataOke = false;
         if(chkEsJeruk.isSelected()&& txtEsJeruk.getText() == "")
             IDataOke = false;
         if(chkEsTeh.isSelected()&& txtEsTeh.getText() == "")
              IDataOke = false;
         
         if(!IDataOke){
             JOptionPane.showMessageDialog(this,
                     "Data Dilengkapi Dahulu");
         }else{
             int nSoto = Integer.parseInt(txtSoto.getText());
             int nSate = Integer.parseInt(txtSate.getText());
             int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
             int nEsTeh = Integer.parseInt(txtEsTeh.getText());
             
             int nTotal = (5000* nSoto)+
                     (10000 * nSate)+(1500 *nEsJeruk)+(2000 *nEsTeh);
             lblTotal.setText("Rp."+nTotal);
             
             
             if(rdoCash.isSelected())
                 lblCaraBayar.setText(rdoCash.getActionCommand());
              if(rdoBCA.isSelected())
                 lblCaraBayar.setText(rdoBCA.getActionCommand());
               if(rdoMandiri.isSelected())
                 lblCaraBayar.setText(rdoMandiri.getActionCommand());
         }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        chkSoto.setSelected(false);
        chkSate.setSelected(false);
        chkEsJeruk.setSelected(false);
        chkEsTeh.setSelected(false);
        txtSoto.setText("0");
        txtSate.setText("0");
        txtEsJeruk.setText("0");
        txtEsTeh.setText("0");
        txtSoto.setEditable(false);
        txtSate.setEditable(false);
        txtEsJeruk.setEditable(false);
        txtEsTeh.setEditable(false);
        rdoCash.setSelected(true);
        lblTotal.setText("Rp. 0");
        lblCaraBayar.setText("Cara Bayar  : UANG CASH");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void rdoMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMandiriActionPerformed
     lblCaraBayar.setText("Cara Bayar : KARTU DEBIT MANDIRI");
    }//GEN-LAST:event_rdoMandiriActionPerformed

    private void rdoBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBCAActionPerformed
      lblCaraBayar.setText("Cara Bayar : KARTU DEBIT BCA");
    }//GEN-LAST:event_rdoBCAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new P_Modul2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCara;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMandiri;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables
}
